services:
    postgres:
        image: postgres:15
        container_name: datawarehouse_postgres
        environment:
            POSTGRES_USER: admin
            POSTGRES_DB: datawarehouse_postgres
        ports:
          - "5432:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data
    etl:
      build: .
      depends_on:
        - postgres
      environment:
        DATABASE_URL: postgresql://admin@postgres:5432/datawarehouse

    pgadmin:
      image: dpage/pgadmin4
      container_name: datawarehouse_pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com 
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80"
volumes:
  postgres_data:
    


        
      