services:
  postgres2:
    image: postgres:15
    container_name: postgres2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydataase
    ports:
      - "5432:5432"
    volumes:
      - postgres2_data:/var/lib/postgresql/postgres_data

volumes:
  postgres2_data:

