services:
  postgres1:
    image: postgres:15
    container_name: postgres1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydataase
    ports:
      - "5432:5432"
    volumes:
      - postgres1_data:/var/lib/postgresql/postgres_data

volumes:
  postgres1_data:

  


